version: '3.7'
services:
  api:
    build: .
    ports:
      - '3000:3000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/books']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
